### ISSUE TITLE
Umlaute werden Fehlerhaft angezeigt

### ISSUE THREAD

**Issue by jannesrudnick** [kiliankoe/vvo#13]
Hey,
ich habe Folgendes Problem:

```
import dvb
import json
import sys  

stop = 'Busbahnhof Deuben'
time_offset = 0 # how many minutes in the future, 0 for now
num_results = 5
city = 'Dresden'

obj = dvb.monitor(stop, time_offset, num_results, city)
print(unicode(obj))
```

Gibt mir:
`[{'arrival': 0, 'line': u'B', 'direction': u'Lockwitz'}, {'arrival': 7, 'line': u'A', 'direction': u'L\xf6btau'}, {'arrival': 11, 'line': u'D', 'direction': u'Bannewitz'}, {'arrival': 12, 'line': u'S 3', 'direction': u'Dresden Hbf'}, {'arrival': 12, 'line': u'F', 'direction': u'Gompitzer H\xf6he'}]`

..aus.
Ich hätte aber gerne das die Umlaute normal angezeigt werden können, gibt es hierfür eine Problemlösung? Wäre sehr dankbar. LG & cooles Projekt

**Comment by kiliankoe** [comment]
Find's immer wieder cool wenn jemand dvbpy benutzt 😊 Das Repo hier ist ne Sammlung an mehreren Infos zum VVO Netzwerk, magst du issues spezifisch zu dvbpy in Zukunft vielleicht in [dem Repo dafür](https://github.com/kiliankoe/dvbpy/issues) aufmachen? Danke 😊 

Wenn ich mich nicht täusche ist das was du beschreibst nur ein Darstellungsproblem auf der Konsole, das Python 2.x betrifft. Die Umlaute sind trotzdem vorhanden und sollten korrekt dargestellt werden, wenn du die einzelnen strings ausgibst. Unicode in Python ist aber auch immer so ne Sache 🙈 

``` python
>>> foo = 'späße'
>>> foo
'sp\xc3\xa4\xc3\x9fe'
>>> print(foo)
späße
```

Meine Empfehlung, nutz' statt Python 2 lieber Python 3. Python 3 gibt's seit mittlerweile 10 Jahren und in 2 Jahren ist das offizielle Ende von Support für Python 2. Jetzt ist ein super Zeitpunkt um da den Sprung zu wagen 😄 Python 3 geht auch mit unicode sinnvoller um.

**Comment by jannesrudnick** [comment]
> magst du issues spezifisch zu dvbpy in Zukunft vielleicht in dem Repo dafür aufmachen?
Huch sorry, da hab mich wohl verklickt. Werde das nächste mal drauf achten.

> Meine Empfehlung, nutz' statt Python 2 lieber Python 3.
Vielleicht hab ich irgendwas übersehen, aber wie stell ist das an? Wenn ich mit `pip install dvb` installiere und dann mein Skript mit Python3 starte bekomme ich die Fehlermeldung das dvb nicht existiert. 

Daraufhin habe ich nachgeschaut gehabt und festgestellt das sich die dvbpy Dateien unter `/usr/local/lib/python2.7/dist-packages` installiert haben, ist das so richtig? 
Fehler da: ``ImportError: No module named 'dvb'``

Ich bin noch ein relativer Anfänger was diesen Themengebiet angeht, testweise nahm ich die Dateien und legte sie nach `/usr/local/lib/python3.5/dist-packages` nach starten meines Skripts mit Python3. Fehlermeldung:

`Traceback (most recent call last):
  File "/opt/bot/dvbt.py", line 2, in <module>
    import dvb
  File "/usr/local/lib/python3.5/dist-packages/dvb/__init__.py", line 1, in <module>
    from .dvb import *
  File "/usr/local/lib/python3.5/dist-packages/dvb/dvb.py", line 3, in <module>
    import pyproj
  File "/usr/local/lib/python3.5/dist-packages/pyproj/__init__.py", line 51, in <module>
    from pyproj import _proj
ImportError: /usr/local/lib/python3.5/dist-packages/pyproj/_proj.so: undefined symbol: _Py_ZeroStruct` 

Wenn ich noch irgendwas hinzufügen soll, sag bescheid.

**Comment by kiliankoe** [comment]
Sorry, hab das hier völlig übersehen 🤦‍♂️ 

Für mich klingt das danach, als ob du lokal sowohl Python 2 als auch Python 3 installiert hast, was ja an sich kein Problem ist, aber die beiden sich in die Quere kommen. `pip --version` gibt vermutlich was mit Python 2 aus? Dann wird ein `pip install dvb` auch dazu führen, dass das Paket für Python 2 installiert wird. Schau mal ob du direkt ein `pip3` (oder `python3 -m pip`) hast und das nutzen kannst.

Alternativ empfiehlt es sich für Python Projekte sehr sog. virtual environments zu nutzen. Damit legt man gleich die Version von Python für ein Projekt fest, linkt sowohl `python` als auch `pip` auf die korrekte Version und installiert Abhängigkeiten nicht global. Hier ist eine kurze Einführung dazu: https://docs.python.org/3/library/venv.html

**Comment by kiliankoe** [comment]
Ich schließe das hier mal, schreib' einfach wenn noch Fragen offen sind 😊
