### ISSUE TITLE
iOS App now released!

### ISSUE THREAD

**Issue by PhilippMatthes** [kiliankoe/vvo#14]
Hi Kilian, I just wanted to tell you that the [iOS App](https://itunes.apple.com/us/app/manni/id1347527695?l=de&ls=1&mt=8) has launched yesterday. Maybe you want to add it to your readme? 😊

**Comment by kiliankoe** [comment]
Congrats! And it's pretty awesome! 👏 

I'll gladly accept a PR if you want the joy of adding it yourself 😄 Otherwise I can of course also do so if you want 😊
