### ISSUE TITLE
Kontakt zu Faplino Dev?

### ISSUE THREAD

**Issue by frauhottelmann** [kiliankoe/vvo#22]
Hat jemand einen Kontakt zu dem Dev von Faplino? Die APP ist jetzt im play store nicht mehr verfügbar. Ich hab zwar noch eine apk hier rumliegen, aber praktisch ist das nicht. Es wäre schön, wenn er (Markus Dietel) den source code freigeben könnte. Dann wär vielleicht ein F-Droid build drin...

**Comment by frauhottelmann** [comment]
Ich hab sogar was gefunden: https://code.google.com/archive/p/faplino/

**Comment by kiliankoe** [comment]
Ein F-Droid Build ist natürlich immer toll, aber die App ist doch nach wie vor im Play Store verfügbar? https://play.google.com/store/apps/details?id=de.faplino

Ansonsten hast du sicherlich auch gesehen, dass an den Commits auf Google Code eine Gmail Adresse steht die zumindest 2014 genutzt wurde. Vielleicht erreicht man dort ja jemanden.

**Comment by frauhottelmann** [comment]
Ich weiß auch nicht so richtig was da mit Google Play nicht stimmt. Mal kann ich die APP finden und mal nicht.
Ich hab mal ne mail an die im store angegebene Mail-Adresse geschickt.

**Comment by frauhottelmann** [comment]
Ja, ist jetzt wieder verfügbar, nachdem ich eine Mail geschickt habe. Er hat geschrieben, dass er das Projekt momentan nicht aus der Hand geben möchte.
