### ISSUE TITLE
manni android app, referenced in `README.md`, not found.

### ISSUE THREAD

**Issue by dreirund** [kiliankoe/vvo#28]
The `README.md` links for `manni` to [https://play.google.com/store/apps/details?id=philippmatthes.com.manni](https://play.google.com/store/apps/details?id=philippmatthes.com.manni). But that gives an error 404 "not found".

Is there a source independent from google?

**Comment by PhilippMatthes** [comment]
The App was removed from distribution. You can delete it from the readme. Sorry for the inconvenience.

**Comment by kiliankoe** [comment]
That's unfortunate, but thanks for the info @PhilippMatthes.
