### ISSUE TITLE
Missing documentation on direct DFI-base API by DVB through http://dfi.dvb.de/ 

### ISSUE THREAD

**Issue by jens-maus** [kiliankoe/vvo#3]
Since a while the DVB is directly providing a WebDFI-based API to allow to show an own web view of a certain station. For example, see here:

https://www.dvb.de/de-de/service/geschaeftskunden/abfahrtsmonitor/

While this WebDFI based solution is usually individually targeted to a certain user (you have to directly register with the DVB) there are certain things in this WebDFI API that can be used to query more information than the current vvo-online.de API allows to extract.

For example, the following view shows a web view of the "Ullersdorfer Platz" Station:

http://dfi.dvb.de/Dfi/Index?hash=8B8AD2D309A9FF86EDA86E346C132F1C

After some short reverse engineering one can actually query the direct data using the following URL:

http://dfi.dvb.de/Dfi/Departures?hash=8B8AD2D309A9FF86EDA86E346C132F1C&stopid=678

This actually returns a similar data array like the vvo-online.de query but with e.g. showing the "Steig" like I mentioned in ticket #2.

One further but trivial URL query (the current time reference) can be queried like this:

http://dfi.dvb.de/Dfi/GetTime

The question of course remains now if this DFI based API might be of any greater use for this project?!? At least I feel we should document its existence.

**Comment by kiliankoe** [comment]
Interesting! I had no idea something like this exists. Thanks for the links 😊 

But yeah, this is definitely something for the list! If you want to you can go ahead and add it in or of course I can, whichever you prefer 🙃

**Comment by jens-maus** [comment]
go ahead

**Comment by kiliankoe** [comment]
Done ✅ 

I linked to this issue to re-use what you wrote above. Might be worth migrating that into the wiki at some point.
