### ISSUE TITLE
Hostname for `Magic Mirror` cannot be resolved.

### ISSUE THREAD

**Issue by dreirund** [kiliankoe/vvo#30]
In `README.md`, `Magic Mirror` links to [http://blog.thomas-bachmann.com/2016/02/magic-mirror-2-0-mit-gestensteuerung.html](http://blog.thomas-bachmann.com/2016/02/magic-mirror-2-0-mit-gestensteuerung.html). But the hostname cannot be resolved.

**Comment by dreirund** [comment]
You might want to link to [https://github.com/skastenholz/MMM-DVB](https://github.com/skastenholz/MMM-DVB) or [https://github.com/MichMich/MagicMirror/wiki/3rd-party-modules](https://github.com/MichMich/MagicMirror/wiki/3rd-party-modules). instead

**Comment by kiliankoe** [comment]
Thanks for checking and the other links! It's a shame that links appear to be dying. I've replaced the one to @thobach's blog with an archive.org link to it and added MMM-DVB to the list 👍
