### ISSUE TITLE
Feature Comparison

### ISSUE THREAD

**Issue by hoodie** [kiliankoe/vvo#4]
Could we have a comparison table that shows which API Endpoints are supported?

**Comment by kiliankoe** [comment]
Yes! There's currently some progress to move some stuff around, but this seems like a good idea. I'm guessing you mean for the libs?

**Comment by kiliankoe** [comment]
Do you mean something along the lines of this?

| | WebAPI | Widgets | EFA | Trias | WebDFI |
|---|---|---|---|---|---|
|dvbjs| ✅ |
|dvbpy|
|dresdner-verkehrsbetriebe|
|DVB|
|dvbrb|
|dvbgo|
|dvb-rs|

It would probably make more sense to throw the basic features on the X-Axis and see which are supported there. But the feature-list is pretty long 😄

**Comment by hoodie** [comment]
yay `rot(table)` svp
