### ISSUE TITLE
Trip Details

### ISSUE THREAD

**Issue by fnep** [kiliankoe/vvo#8]
Hello and thank you for this great project. 

I want to add some documentation for a request I just found useful. Unfortunately there seems to be no good way to contribute to the wiki. Would be better to have this as markdown files in the repo. Anyway now as an issue. 

-> https://github.com/kiliankoe/vvo/wiki/WebAPI

# Trip Details

Get the details about the stations involved in a particular trip. 

## Request

POST https://webapi.vvo-online.de/dm/trip

### JSON Body:

Name | Type | Description | Required
-- | -- | -- | --
tripid | String | The "id" received from the departure monitor (Departures[*]. Id).  | Yes
time | String| The current time as unix timestamp plus timezone. Has to be in the future. Most likely from a departure monitor response (Departures[\*]. RealTime / Departures[\*]. ScheduledTime). | Yes
stopid | String | ID of a stop in the route. This stop will be marked with Position=Current in the response. | Yes
mapdata | Bool | Unknown. Seems to have no effect.  | No

```
curl -X "POST" "https://webapi.vvo-online.de/dm/trip" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "tripid": "71313709",
  "time": "/Date(1512563081000+0100)/",
  "stopid": "33000077"
}'
```

## Response
```
{
  "Stops": [
    ...
    {
      "Id": "33000076",
      "Place": "Dresden",
      "Name": "Laibacher Straße",
      "Position": "Previous",
      "Platform": {
        "Name": "2",
        "Type": "Platform"
      },
      "Time": "\/Date(1512563021000+0100)\/"
    },
    {
      "Id": "33000077",
      "Place": "Dresden",
      "Name": "Großglocknerstraße",
      "Position": "Current",
      "Platform": {
        "Name": "2",
        "Type": "Platform"
      },
      "Time": "\/Date(1512563081000+0100)\/"
    },
    {
      "Id": "33000078",
      "Place": "Dresden",
      "Name": "Friedhof Leuben",
      "Position": "Next",
      "Platform": {
        "Name": "2",
        "Type": "Platform"
      },
      "Time": "\/Date(1512563141000+0100)\/"
    },
    ...
  ],
  "Status": {
    "Code": "Ok"
  },
  "ExpirationTime": "\/Date(1512565171371+0100)\/"
}
```

**Comment by kiliankoe** [comment]
Hey 👋😊 

My intention with the wiki was to aid in collaboration, definitely not the opposite. Also, discoverability of a wiki just isn't that great either. Moving the content from there into separate markdown files in the repo itself definitely seems like a sensible idea. 

Huge thanks for the documentation of the webapi/dm/trip endpoint! I'll see what I can do about pulling the other content out of the wiki either tonight or sometime the next few days. Then this can be included right with the rest 😊

**Comment by kiliankoe** [comment]
Just moved the previous wiki content to the repo into `documentation/`. I'd love to include your changes via PR 😊

**Comment by fnep** [comment]
This is great news. When i find some time i will see if i can add details for the other open requests, too.
